version: '3.8'

services:
  oral:
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/ttttt?useUnicode=true&characterEncoding=utf-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 136623
    networks:
      - mynet

  db:
    image: mysql:8.0.27
    environment:
      MYSQL_ROOT_PASSWORD: 136623
      MYSQL_DATABASE: ttttt
    ports:
      - "3306:3306"
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    networks:
      - mynet
    command: --bind-address=0.0.0.0

  oral_front:
    build:
      context: src/main/resources/admin/admin
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    networks:
      - mynet

networks:
  mynet:
